### PR TITLE
feat: add assignPublicIp setting

### LINKED ISSUE #262: Allow possibility of assigning public IP
Hi! Nice and handy construct!

Would it be possible to expose a setting to assign a public IP to the task? We would like to run it in a public subnet (without NAT or private endpoint)? We can see that it's defaulted to `DISABLED` here: https://github.com/pahud/cdk-fargate-run-task/blob/main/src/run-task.ts#L151

### PR DESCRIPTION
**Pull request by stoft**
Fixes #262 

### Problem

Sometimes we want to run in a public subnet with access to the internet, without a NAT Gateway, but then we need a public IP.

### Solution

Add setting for assigning a public IP.

<a href="https://gitpod.io/#https://github.com/pahud/cdk-fargate-run-task/pull/263"></a>

### CODE REVIEW

**Comment by stoft** [comment]
bump

**Comment by stoft** [comment]
@pahud any chance of some help here? I don't know how to get this to progress further.

**Comment by pencil** [comment]
@pahud Could you please merge this?

**Comment by pahud** [comment]
sorry for being late :-)

**Pull request merged**
